[versions]
agp = "8.3.0-rc01"
junit = "4.13.2"
junitVersion = "1.1.5"
espressoCore = "3.5.1"
appcompat = "1.6.1"
material = "1.11.0"
activity = "1.8.0"
constraintlayout = "2.1.4"
materialVersion = "1.9.0"
zego_uikit_prebuilt_call_android = "2.10.5"
zego_uikit_signaling_plugin_android = "2.4.0"

[libraries]
junit = { group = "junit", name = "junit", version.ref = "junit" }
ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
material-v190 = { module = "com.google.android.material:material", version.ref = "materialVersion" }
zego_uikit_prebuilt_call_android = { module = "com.github.ZEGOCLOUD:zego_uikit_prebuilt_call_android", version.ref = "zego_uikit_prebuilt_call_android" }
zego_uikit_signaling_plugin_android = { module = "com.github.ZEGOCLOUD:zego_uikit_signaling_plugin_android", version.ref = "zego_uikit_signaling_plugin_android" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }

